# Site
repository: Pipi-Olo/Pipi-Olo.github.io
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: 문규환
title: Server Developer
email: pipiolo1024@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username: Pipi-Olo
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: 문규환
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url : Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/icon.jpg
about_content: | # this will include new lines to allow paragraphs

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Ahnlab
        sub_title: Server Developer
        caption: 2022.10 ~ Now
        link: https://www.ahnlab.com
        quote: >
          Artificial Intelligence Team
        description: | # this will include new lines to allow paragraphs
          * 행위 데이터를 통한 악성 진단 ML 모델 관련 서비스 개발 및 운영
          * Milvus, ZooKeeper & Kafka, 빌드 머신 담당자
          * Kubernetes & Helm 기반 서비스 개발 및 운영
  - title: Technology
    layout: list
    content:
      - layout: left
        title: Frontend
        #        sub_title: Qualifications (eg. BA Performing Arts)
        #        caption: Date Range (eg. 2016 - 2019)
        #        quote: >
        #          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          * Streamlit (Python)
      - layout: left
        title: Backend
#        sub_title: Qualifications (eg. BA Performing Arts)
#        caption: Date Range (eg. 2016 - 2019)
#        quote: >
#          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          * Java
            * Spring Boot, Spring MVC, Spring Data JPA
            * JPA / Hibernate, Querydsl
            * Gradle
          * Scala
            * Finagle
            * SBT
          * Python
            * Celery, Flower
      - layout: left
        title: DevOps
#        sub_title: Qualifications (eg. BA Performing Arts)
#        caption: Date Range (eg. 2016 - 2019)
#        quote: >
#          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          * HTTP, Apache Thrift
          * Cassandra, MinIO, Milvus
          * ZooKeeper, Kafka
          * Kubernetes, Helm, Rancher
          * Linux Server (CentOS 7, Rocky Linux 8)
      - layout: left
        title: Data Engineering
#        sub_title: Qualifications (eg. BA Performing Arts)
#        caption: Date Range (eg. 2016 - 2019)
#        quote: >
#          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          * (Py) Spark
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
        # other value (or no value) means no border will be displayed
        title: pipiolo-springboot2-webservice
#        link:
#        link_text: Link Text
        additional_links:
          - title: Pipi-Olo/pipiolo-springboot2-webservice
            icon: fab fa-github
            url: https://github.com/Pipi-Olo/pipiolo-springboot2-webservice
#          - title: Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          * 프로젝트 Beyond 이동욱 저자 - '스프링 부트와 AWS로 혼자 구현하는 웹 서비스' 
          * AWS 을 이용한 서버 운영 및 Code Deploy 를 통한 무중단 배포
  - title: Education
    layout: list
    content:
      - layout: left
        title: inflearn-sprig
#        sub_title: Server Developer
        caption: 2022.04 ~ 2022.10
#        link:
        quote: >
          Java Spring Web Backend
        description: | # this will include new lines to allow paragraphs
          * Java JPA & Spring Data JPA, Querydsl 교육
          * Spring Boot, Spring MVC 등 Spring 교육
      - layout: left
        title: 중앙대학교 컴퓨터공학부
#        sub_title:
        caption: 2015.03 ~ 2019.02
        link: https://www.cau.ac.kr
#        quote: >
#        description: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
